-f files/core.f
rtl/soc/rv32_tcm.sv
rtl/soc/rv32_mtimer.sv
rtl/soc/rv32_uart.sv
rtl/soc/rv32_gpio.sv
rtl/soc/rv32_mem_demux.sv
rtl/soc/soc_tcm_top.sv
rtl/fpga/reset_sync.sv
tb/common/rv32_tb_pkg.sv
tb/common/rv32_delayed_mem.sv
tb/integration/tb_rv32_core.sv
tb/integration/tb_csr_core.sv
tb/integration/tb_timer_interrupt_core.sv
tb/integration/tb_soc_tcm_top.sv
tb/integration/tb_pipeline_forwarding.sv
tb/integration/tb_pipeline_memory_wait.sv
tb/integration/tb_core_control_flow.sv
tb/integration/tb_baremetal.sv
tb/integration/tb_freertos_soc.sv
